core/urls.py
from django.urls import path
from core import views


app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about_view, name="about"),
    path("product/", views.product_view, name="product"),
    path("blog/", views.blog_view, name="blog"),
    path("contact/", views.contact_view, name="contact"),
    # path("services/", views.about, name="about"),
]

my_wine_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('user/', include("userauths.urls")),
    path('classifier/', include("classificator.urls")),
]

# In other to our static file and pictures work, we should set it like that
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, documents_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views


app_name = "userauths"



urlpatterns = [
    path('sign-up/', views.register_view, name="register"),
    path('sign-in/', views.login_view, name="login"),
    # path('sign-out/', views.logout_view, name="sign-out"),
]

core/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField  # for id generation
from django.utils.html import mark_safe
from userauths.models import User

STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("in_review", "In Review"),
    ("rejected", "Rejected"),
    ("published", "Published"),
)

RATING = (
    (1, "⭐✰✰✰✰"),
    (2, "⭐⭐✰✰✰"),
    (3, "⭐⭐⭐✰✰"),
    (4, "⭐⭐⭐⭐✰"),
    (5, "⭐⭐⭐⭐⭐"),
)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)


# Create your models here.

class Category(models.Model):
    cId = ShortUUIDField(unique=True, length=10, max_length=20, prefix="cat", alphabet="abcdefghi12345")
    title = models.CharField(max_length=100, default="clothes")
    image = models.ImageField(upload_to="category", default="category.jpg")

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


class Staff(models.Model):
    stId = ShortUUIDField(unique=True, length=10, max_length=20, prefix="ven", alphabet="abcdefghi67891")

    name = models.CharField(max_length=100, default="Myname")
    image = models.ImageField(upload_to=user_directory_path, default='staff.jpg')
    description = models.TextField(null=True, blank=True, default="Great team")

    adress = models.CharField(max_length=100, default="135, Main street Moscow")
    contact = models.CharField(max_length=100, default="+7(977) 657 689")
    chat_resp_time = models.CharField(max_length=100, default="100")
    authentic_rating = models.CharField(max_length=100, default="100")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name_plural = "Staffs"

    def staff_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.name


class Product(models.Model):
    pId = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghi12345")

    title = models.CharField(max_length=100, default="Adidas")
    image = models.ImageField(upload_to=user_directory_path, default='product.jpg')
    description = models.TextField(null=True, blank=True, default="Best wine")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    price = models.DecimalField(max_digits=9999999, decimal_places=2, default="2.99")
    old_price = models.DecimalField(max_digits=9999999, decimal_places=2, default="3.99")

    specification = models.TextField(null=True, blank=True)

    product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)

    sku = ShortUUIDField(unique=True, length=4, max_length=20, prefix="sku", alphabet="123456789")

    date = models.DateTimeField(auto_now_add=True)
    date = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Products"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

    def get_percentage(self):
        new_price = (self.price / self.old_price) * 100
        return new_price

# To display images of a given product
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images", default="product.jpg")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Images"


# ##service

# for service provided by us
class Service(models.Model):
    sId = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghi12345")

    title = models.CharField(max_length=100, default="Adidas")
    image = models.ImageField(upload_to=user_directory_path, default='product.jpg')
    description = models.TextField(null=True, blank=True, default="The product")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    specification = models.TextField(null=True, blank=True)
    # tags = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True)

    service_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

    status = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)

    sku = ShortUUIDField(unique=True, length=4, max_length=20, prefix="sku", alphabet="123456789")

    date = models.DateTimeField(auto_now_add=True)
    date = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Services"

    def service_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

# For product review
class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Reviews"

    def __str__(self):
        return self.product.title

    def get_rating(self):
        return self.rating

core/views.py
from django.shortcuts import render
from django.http import HttpRequest

# Create your views here.
def home(request):
    
    return render(request, 'core/index.html')

def about_view(request):
    return render(request, 'core/about.html')

def product_view(request):
    return render(request, 'core/product.html')

def blog_view(request):
    return render(request, 'core/blog.html')


def services_view(request):
    return render(request, 'core/services.html')

def contact_view(request):
    return render(request, 'core/contact.html')

core/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Liquor Store - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,200;0,300;0,400;0,500;0,700;0,800;1,200;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

    <link  href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link  href="{% static 'css/animate.css' %}" rel="stylesheet">
    
    <link  href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <link  href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet">
    <link  href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
    
    <link  href="{% static 'css/flaticon.css' %}" rel="stylesheet">
    <link  href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body>

  	<div class="wrap">
			<div class="container">
				<div class="row">
					<div class="col-md-6 d-flex align-items-center">
						<p class="mb-0 phone pl-md-2">
							<a href="#" class="mr-2"><span class="fa fa-phone mr-1"></span> +00 1234 567</a> 
							<a href="#"><span class="fa fa-paper-plane mr-1"></span> youremail@email.com</a>
						</p>
					</div>
					<div class="col-md-6 d-flex justify-content-md-end">
						<div class="social-media mr-4">
			    		<p class="mb-0 d-flex">
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-dribbble"><i class="sr-only">Dribbble</i></span></a>
			    		</p>
		        </div>
		        <div class="reg">
		        	<p class="mb-0">
                <a href="{% url 'userauths:register' %}" class="mr-2">Sign Up</a>
                 <a href="{% url 'userauths:login' %}">Log In</a>
                </p>
		        </div>
					</div>
				</div>
			</div>
		</div>
    
	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">Wine <span>Checker</span></a>
	      <div class="order-lg-last btn-group">
          <a href="#" class="btn-cart dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          	<span class="flaticon-shopping-bag"></span>
          	<div class="d-flex justify-content-center align-items-center"><small>3</small></div>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            {% comment %} <div class="align-items-center" style="background-image: url({% static 'images/about.jpg' %})"></div> {% endcomment %}

				    <div class="dropdown-item d-flex align-items-start" href="#">
                        <div class="img" style="background-image: url({% static 'images/prod-1.jpg' %})"></div>

				    	{% comment %} <div class="img" style="background-image: url({% static 'images/prod-1.jpg %})"></div> {% endcomment %}
				    	<div class="text pl-3">
				    		<h4>Bacardi 151</h4>
				    		<p class="mb-0"><a href="#" class="price">$25.99</a><span class="quantity ml-3">Quantity: 01</span></p>
				    	</div>
				    </div>
				    <div class="dropdown-item d-flex align-items-start" href="#">
				    	<div class="img" style="background-image: url({% static 'images/prod-2.jpg' %})"></div>
				    	<div class="text pl-3">
				    		<h4>Jim Beam Kentucky Straight</h4>
				    		<p class="mb-0"><a href="#" class="price">$30.89</a><span class="quantity ml-3">Quantity: 02</span></p>
				    	</div>
				    </div>
				    <div class="dropdown-item d-flex align-items-start" href="#">
				    	<div class="img" style="background-image: url({% static 'images/prod-3.jpg' %})"></div>
				    	<div class="text pl-3">
				    		<h4>Citadelle</h4>
				    		<p class="mb-0"><a href="#" class="price">$22.50</a><span class="quantity ml-3">Quantity: 01</span></p>
				    	</div>
				    </div>
				    <a class="dropdown-item text-center btn-link d-block w-100" href="cart.html">
				    	View All
				    	<span class="ion-ios-arrow-round-forward"></span>
				    </a>
				  </div>
        </div>

	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item active"><a href="{% url 'core:home' %}" class="nav-link">Home</a></li>
	          <li class="nav-item"><a href="{% url 'core:about' %}" class="nav-link">About</a></li>
	          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url 'core:product' %}" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Products</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
              	<a class="dropdown-item" href="{% url 'core:product' %}" >Products</a>
                <a class="dropdown-item" href="product-single.html">Single Product</a>
                <a class="dropdown-item" href="cart.html">Cart</a>
                <a class="dropdown-item" href="checkout.html">Checkout</a>
              </div>
            </li>
	          <li class="nav-item"><a href="{% url 'core:blog' %}" class="nav-link">Blog</a></li>
	          <li class="nav-item"><a href="{% url 'core:contact' %}" class="nav-link">Contact</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->


    {% block content %}


    {% endblock content %}




    <footer class="ftco-footer">
        <div class="container">
          <div class="row mb-5">
            <div class="col-sm-12 col-md">
              <div class="ftco-footer-widget mb-4">
                <h2 class="ftco-heading-2 logo"><a href="#">Liquor <span>Store</span></a></h2>
                <p>Far far away, behind the word mountains, far from the countries.</p>
                <ul class="ftco-footer-social list-unstyled mt-2">
                  <li class="ftco-animate"><a href="#"><span class="fa fa-twitter"></span></a></li>
                  <li class="ftco-animate"><a href="#"><span class="fa fa-facebook"></span></a></li>
                  <li class="ftco-animate"><a href="#"><span class="fa fa-instagram"></span></a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-12 col-md">
              <div class="ftco-footer-widget mb-4 ml-md-4">
                <h2 class="ftco-heading-2">My Accounts</h2>
                <ul class="list-unstyled">
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>My Account</a></li>
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Register</a></li>
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Log In</a></li>
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>My Order</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-12 col-md">
              <div class="ftco-footer-widget mb-4 ml-md-4">
                <h2 class="ftco-heading-2">Information</h2>
                <ul class="list-unstyled">
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>About us</a></li>
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Catalog</a></li>
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Contact us</a></li>
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Term &amp; Conditions</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-12 col-md">
               <div class="ftco-footer-widget mb-4">
                <h2 class="ftco-heading-2">Quick Link</h2>
                <ul class="list-unstyled">
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>New User</a></li>
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Help Center</a></li>
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Report Spam</a></li>
                  <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Faq's</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-12 col-md">
              <div class="ftco-footer-widget mb-4">
                  <h2 class="ftco-heading-2">Have a Questions?</h2>
                  <div class="block-23 mb-3">
                    <ul>
                      <li><span class="icon fa fa-map marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                      <li><a href="#"><span class="icon fa fa-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                      <li><a href="#"><span class="icon fa fa-paper-plane pr-4"></span><span class="text">info@yourdomain.com</span></a></li>
                    </ul>
                  </div>
              </div>
            </div>
          </div>
        </div>
        <div class="container-fluid px-0 py-5 bg-black">
            <div class="container">
                <div class="row">
                <div class="col-md-12">
          
                  <p class="mb-0" style="color: rgba(255,255,255,.5);"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
              </div>
            </div>
        </div>
      </footer>


 <!-- loader -->
 <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


 <script src="{% static 'js/jquery.min.js' %}"></script>
 <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
 <script src="{% static 'js/popper.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
 <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
 <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
 <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
 <script src="{% static 'js/owl.carousel.min.js' %}"></script>
 <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
 <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
 <script src="{% static 'js/scrollax.min.js' %}"></script>
 <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
 <script src="{% static 'js/google-map.js' %}"></script>
 <script src="{% static 'js/main.js' %}"></script>


 
</body>
</html>